### ISSUE TITLE
About partial sort/topk

### ISSUE THREAD

**Issue by WilliamTambellini** [intel/x86-simd-sort#10]
Hi
Would there be any blocker in order to implement an option to do partial sorting (sometimes called 'topk') ?
https://en.cppreference.com/w/cpp/algorithm/partial_sort
I know it s usually done with heap sort and this project is more into quicksort but still.
Kind
WT
ref:
https://arrayfire.org/docs/group__stat__func__topk.htm#gsc.tab=0
https://pytorch.org/docs/stable/generated/torch.topk.html

**Comment by r-devulap** [comment]
Hi, I dont see a blocker, but this wasn't in my to do list. On the top of my head I cant think of an immediate way to implement this in SIMD. Feel free to point me to resources or even better: submit a pull request :)

**Comment by WilliamTambellini** [comment]
WIP
https://github.com/intel/x86-simd-sort/pull/13

**Comment by r-devulap** [comment]
@WilliamTambellini Any feedback on partial/topk sort? Just wanted to know if it was useful or not.

**Comment by WilliamTambellini** [comment]
sorry took time, trying ... Tks.
