### ISSUE TITLE
argsort and AVX2

### ISSUE THREAD

**Issue by MohamadAnabtawe-Opteamizer** [intel/x86-simd-sort#107]
Hi,
Wanted to ask if there are any plans for argsort implementation with AVX2?

**Comment by r-devulap** [comment]
HI @MohamadAnabtawe-Opteamizer Thanks for you interest. It is coming up soon, #102 is the first step towards having generic code to help implement AVX2 version.

**Comment by r-devulap** [comment]
closing this, #119 has been merged.
