### ISSUE TITLE
Any plans to implement on AVX/AVX2?  

### ISSUE THREAD

**Issue by danielbraun89** [intel/x86-simd-sort#11]
Any plans to implement on AVX/AVX2 as well, in order to improve availability?

**Comment by oscarbg** [comment]
+1

**Comment by r-devulap** [comment]
yeah, that is in the plan and would be a great addition to the AVX-512 code. Contributions are welcome :)

**Comment by r-devulap** [comment]
see #60

**Comment by r-devulap** [comment]
#60 and #93 adds AVX2 versions of quicksort, quickselect and partial sort for 32-bit and 64-bit data types. Should I consider this done?

**Comment by r-devulap** [comment]
Closing as completed.
