### ISSUE TITLE
Lower-version gcc can`t support Optimization Pragmas.

### ISSUE THREAD

**Issue by ruclz** [intel/x86-simd-sort#41]
We attempt to merge avx512-sort to oceanbase, compared with std::sort, the avx512-sort has an obvious perf. improvement.  But there is a problem when merging new x86_simd_sort into oceanbase. We found that, you added some GCC Optimization Pragmas in the latest version of x86-simd-sort. Such as “#pragma GCC unroll 8” . The default GCC version of oceanbase is gcc5.2.0, it seems that this gcc doesn`t support  these pragmas. The error is like this:
![image](https://github.com/intel/x86-simd-sort/assets/46258124/d65ca843-33c0-4691-b48b-ef6d089f06fd)

Please help to fix.

**Comment by r-devulap** [comment]
See #46 and let me know if it resolves your issue.
