### ISSUE TITLE
A question about hardware implementation of quick-sort in future Intel CPUs

### ISSUE THREAD

**Issue by antoinecarme** [intel/x86-simd-sort#51]
Hi,

If I understand well, this is a software C++ implementation of a quick sort using hardware AVX vector instructions. 

A lot of CPUs now have instructions for cryptography, hashing etc. And Intel does.

Is there a roadmap at intel , even for the next 10 years, to have a basic quick sort performed in hardware the same way a hash is computed ? I know the hardware implementation is complex. 

We need the hardware to move closer to what standard software libraries provide as a service level and a hardware sort is big game changer (I think of Data processing, Machine learning, binning, quantization, etc).

**Comment by r-devulap** [comment]
Hi @antoinecarme. Thank you for your question but unfortunately I have no idea. An instruction to sort zmm register would be useful though :)

**Comment by antoinecarme** [comment]
@r-devulap 

Thanks for your answer. 

I was just thinking how our code would be easier if all D. Knuth sorting algorithms were implemented inside CPUs as a sort extension besides AVX (ASX ?).  Let alone the speedup improvements for numpy etc.
