### ISSUE TITLE
Argsort Adaptation

### ISSUE THREAD

**Issue by samster25** [intel/x86-simd-sort#7]
Amazing work! I was wondering if it would be possible to adapt the qsort kernels for an argsort. So also returning the indices that would make the original array sorted. (I believe you can do this with std::sort by sorting `pair<value, size_t>` where `size_t` is the original index) Would love to help out if it's feasible!

**Comment by r-devulap** [comment]
Hi, we are working on adding key-value sort (see PR https://github.com/intel/x86-simd-sort/pull/2) and I want to add `argsort `as well. Pull requests are welcome if you want to work on it!

**Comment by samster25** [comment]
@r-devulap Amazing! I'll wait till that lands and then help out

**Comment by r-devulap** [comment]
See #34 @samster25

**Comment by samster25** [comment]
Thanks @r-devulap Will looking into integration!

**Comment by r-devulap** [comment]
@samster25 argsort for 32-bit and 64-bit dtype has been merged. Were you able to integrate it? Just curious to hear your feedback and what sort of workload you are using it in.

**Comment by r-devulap** [comment]
Closed, as completed.

**Comment by samster25** [comment]
Hi @r-devulap, Sorry for the delay. I was planning on taking a look in our next sprint! Our plan is to build a Rust crate that wraps this code base. Our use case is we're building a Distributed DataFrame called [daft](https://github.com/Eventual-Inc/Daft) (built in Rust) and we would love to leverage SIMD for our sorts and partitioning algorithms. Thanks again for the hardwork! :)

**Comment by r-devulap** [comment]
@samster25 quick ping to check if you have had time to use any of the simd sort methods in daft?
