### ISSUE TITLE
Question regarding renaming `core` to `_core`

### ISSUE THREAD

**Issue by mtsokol** [intel/x86-simd-sort#78]
Hi!
In the https://github.com/numpy/numpy/pull/24634 PR, `numpy.core` is being renamed to `numpy._core` which affects `.github/workflows/build-numpy.yml` file here. 

Would renaming `core` path to `_core` work here? Or do you need to run the CI against other numpy versions?

**Comment by r-devulap** [comment]
@mtsokol thanks for reaching out. I think renaming core to _core would work just fine. I can update our CI once your PR is merged.

**Comment by mtsokol** [comment]
Hi @r-devulap, https://github.com/numpy/numpy/pull/24634 has been merged!

**Comment by r-devulap** [comment]
thank you. I have updated our CI with that change. See #87
